"""empty message

Revision ID: 951769debddc
Revises: 591691208856
Create Date: 2017-06-11 15:19:43.805024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951769debddc'
down_revision = '591691208856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('delete_flag', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'delete_flag')
    # ### end Alembic commands ###
