"""empty message

Revision ID: fb9d40e602f3
Revises: 951769debddc
Create Date: 2017-06-11 15:40:56.391939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb9d40e602f3'
down_revision = '951769debddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('label_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'article_ibfk_1', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'label', ['label_id'], ['id'])
    op.drop_column('article', 'lable_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('lable_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key(u'article_ibfk_1', 'article', 'label', ['lable_id'], ['id'])
    op.drop_column('article', 'label_id')
    # ### end Alembic commands ###
